### ISSUE TITLE
What does "Images under cursor" (lowercase) do?

### ISSUE THREAD

**Issue by a-raccoon** [zopieux/images-under-cursor#1]
I can't identify what clicking on this menu item is supposed to do.  Maybe it should be renamed or removed.  "Images under cursor" appears to be a lowercase duplicate menu item of "Images Under Cursor".

https://github.com/Zopieux/chrome-images-under-cursor/blob/6f778b1fcb16fd756b685373644b1fa95e68fea4/src/_locales/en/messages.json#L2

**Comment by zopieux** [comment]
As the name suggests, it is used in the contextual menu (right click) to actually run the image search and display results.
It uses a different case because *Image Under Cursor* is the app name (title-case because it's standard in English for brand stuff/headlines) while *Images under cursor* is the actual *action* of finding images, as in *Get me those images*.

I could rename the app lowercase but I don't see any benefit, and I certainly don't want a title case in the contextual menu. Thanks for your suggestion! :smile:

**Comment by a-raccoon** [comment]
I still don't understand what it means.  Please explain it.  What do each of these similarly-named menu options do when I click upon either?  How would it be explained in a help documentation?

![image](https://user-images.githubusercontent.com/1052090/33023704-42778732-cdc6-11e7-88c4-e95b71f637e9.png)

**Comment by zopieux** [comment]
The first item is a Chrome built-in that goes to the extension page.
The second one is there because I use the "context menu" feature of Chrome extensions, so you can have the action when right-clicking. The action appearing in this menu is a side-effect I don't think I can disable. I suggest you hide the icon because this menu won't ever be useful: there are no extension options and you need to point with your mouse for the action to be useful.

Note with the latest version (0.5) you can also use Ctrl-Shift-F or another shortcut to invoke the image search.
